name:                contra
version:             0.1.0.0
github:              "SophieBosio/contra"
license:             BSD-3-Clause
author:              "Sophie Adeline Solheim Bosio"
maintainer:          "sophie.bosio@outlook.com"
copyright:           "2023 Sophie Adeline Solheim Bosio"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            A friendly functional laguage for finding counterexamples
# category:            Programming Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/SophieBosio/contra#readme>

dependencies:
- base              >= 4.7   && < 5
- containers        >= 0.6.7 && <= 0.7.0
- mtl               >= 2.2   && < 2.3
- parsec            >= 3.1   && < 3.2
- sbv               >= 10.0  && < 10.4
- tasty-quickcheck  >= 0.10  && < 0.11

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
#- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
#- -Wredundant-constraints

library:
  source-dirs: src

executables:
  contra:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - contra
    - sbv               >= 10.0  && < 10.4
    - tasty             >= 1.4   && < 1.5

tests:
  contra-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - contra
    - sbv               >= 10.0  && < 10.4
    - tasty             >= 1.4  && < 1.5
    - tasty-hunit       >= 0.10 && < 0.11
