name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ['2.13.1']
        os: [ubuntu-latest]
    name: Using Stack version ${{ matrix.stack }}
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Stack
        uses: haskell/actions/setup@v1
        with:
          stack-version: ${{ matrix.stack }}

      - name: Versions
        run: |
          stack --version
          ghc --version
          cabal --version

      - name: Initialize Stack
        run: stack setup

      - name: Build and test with Stack
        run: |
          stack build --test --bench --no-run-benchmarks --no-run-tests --pedantic

      - name: Package list
        run: |
          stack exec ghc-pkg list || true
